markdown:         redcarpet
permalink:        pretty
exclude:          ['less','scss','*.json','Gruntfile.js','bower_components','node_modules']
source:           ./docs
destination:      ./_gh_pages
encoding:         UTF-8
title:            Drawer
description:      A small CSS3 and jQuery plugin for app style drawer menu.
url:              http://git.blivesta.com/drawer/
repo:             drawer
repo_url:         https://github.com/blivesta/drawer
author:           blivesta
author_url:       http://blivesta.com
twitter:          blivesta
tag:              jquery,css3
git_fork_btn:     http://ghbtns.com/github-btn.html?user=blivesta&amp;repo=drawer&amp;type=fork&amp;count=true
git_star_btn:     http://ghbtns.com/github-btn.html?user=blivesta&amp;repo=drawer&amp;type=watch&amp;count=true
git_follow_btn:   http://ghbtns.com/github-btn.html?user=blivesta&type=follow&count=false
